export const SET_TOTALCOUNT = 'SET_TOTALCOUNT';
export const CORRECTCOUNT_PLUS = 'CORRECTCOUNT_PLUS';
export const ACTIVE_QUESTION_INDEX_PLUS = 'SET_ACTIVE_QUESTION_INDEX';
export const RESET_ACTIVE_QUESTION_INDEX = 'RESET_ACTIVE_QUESTION_INDEX';
export const SET_ANSWERED = 'SET_ANSWERED';
export const SET_ANSWER_CORRECT = 'SET_ANSWER_CORRECT';
